/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.AbstractObject;
import domen.RezervacijaSkija;
import domen.StavkaRezervacijeSkija;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.forme.ModelRezervacija;

/**
 *
 * @author Nadja
 */
public class FrmRezervacijePrikaz extends javax.swing.JFrame {

    List<AbstractObject> listaRezervacija;
    JFrame parent;

    public void setParent(JFrame parent) {
        this.parent = parent;
    }

    /**
     * Creates new form FrmRezervacijePrikaz
     */
    public FrmRezervacijePrikaz() {
        initComponents();
        srediFormu();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Pretrazi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezervacije);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnIzmeni)
                        .addGap(165, 165, 165)
                        .addComponent(btnObrisi)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        if (tblRezervacije.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(parent, "Odaberite rezervaciju!");
        } else {
            RezervacijaSkija rez = (RezervacijaSkija) listaRezervacija.get(tblRezervacije.getSelectedRow());
            FrmRezervacijaParaSkija fmr = new FrmRezervacijaParaSkija(rez);
            fmr.setParent(this);
            //this.setVisible(false);
            fmr.setVisible(true);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String pretraga = jTextField1.getText();
            if (pretraga.isEmpty()) {
                listaRezervacija = Kontroler.getInstance().ucitajListuRezervacija();
            } else {
                listaRezervacija = Kontroler.getInstance().pretraziRezervacije(pretraga);
            }
            ModelRezervacija mpr = (ModelRezervacija) tblRezervacije.getModel();
            mpr.setListaRezervacija(listaRezervacija);
            mpr.fireTableDataChanged();
            if (listaRezervacija.size() == 0) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje rezervaciju!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
        if (tblRezervacije.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(parent, "Odaberite rezervaciju!");
        } else {

            try {
                RezervacijaSkija rez = (RezervacijaSkija) listaRezervacija.get(tblRezervacije.getSelectedRow());
                List<StavkaRezervacijeSkija> stavke = rez.getListaStavki();
                if (!stavke.isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Ne mozete obrisati rezervaciju dok ne obrisete skije tj stavke za tu rezervaciju!");
                    int result = JOptionPane.showConfirmDialog(this, "Da li zelite da obrisete sve stavke rezervacije?", "Potvrda", JOptionPane.YES_NO_OPTION);
                    if (result == JOptionPane.YES_OPTION) {
                        for (StavkaRezervacijeSkija stavkaRezervacijeSkija : stavke) {
                            System.out.println(stavke.size() + "44444444444444");
                            int proslo = Kontroler.getInstance().obrisiStavkuRezervacije(stavkaRezervacijeSkija);
                            if (proslo == 1) {
                                System.out.println("USLO U IF");
                                stavke.remove(stavkaRezervacijeSkija);
                                System.out.println("IZBRISALO IZ LISTE");
                            }
                        }

                    } else {
                        return;
                    }

                }
                rez.setListaStavki(stavke);
                System.out.println(rez.getListaStavki().size() + "Da li je lista stavki praznaaa?????");
                List<AbstractObject> listaPosleBris = Kontroler.getInstance().obrisiRezervaciju(rez);
                ModelRezervacija mpr = (ModelRezervacija) tblRezervacije.getModel();
                mpr.setListaRezervacija(listaPosleBris);
                mpr.fireTableDataChanged();
                JOptionPane.showMessageDialog(rootPane, "Sistem je uspesno obrisao rezervaciju", "Brisanje rezervacije", JOptionPane.INFORMATION_MESSAGE);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Sistem ne moze da obrise rezervaciju!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRezervacijePrikaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblRezervacije;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            listaRezervacija = Kontroler.getInstance().ucitajListuRezervacija();
            ModelRezervacija m = new ModelRezervacija(listaRezervacija);
            tblRezervacije.setModel(m);
        } catch (Exception ex) {
            Logger.getLogger(FrmRezervacijePrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
